language: node_js

sudo: false

cache:
  apt: true
  directories:
    - node_modules


node_js: stable

install:
  - yarn install
  - cd ./test/smoke/template
  - yarn install
  - cd ../../../

scripts:
  - npm test

